CoachMate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .settings import base, dev, prod
from home.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^teams/', include('teams.urls')),
]

if base.DEBUG:
    urlpatterns += static(dev.STATIC_URL, document_root=dev.STATIC_ROOT)
    urlpatterns += static(dev.MEDIA_URL, document_root=dev.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^settings/$', views.settings, name='settings'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect
from CoachMate.settings.base import DEBUG

# Homepage

def home(request):
    if request.user.is_authenticated():
        return redirect('teams:teamList')
    else:
        if DEBUG:
            return render(request, 'home/homepage.html', {})
        else:
            return render(request, 'home/homepage.min.html', {})

home/templates/home/homepage.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="Henry Gridley">

    <title>CoachMate</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'bootstrap/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'home/css/homepage.css' %}" rel="stylesheet">

    <script src="{% static 'bootstrap/js/ie-emulation-modes-warning.js' %}"></script>
    <script src="{% static 'home/js/smoothScroll.js' %}"></script>
  </head>

  <body>
    <!-- Navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">CoachMate</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <!-- Log in & sign up -->
          <div class="nav navbar-nav navbar-right">
            <a class="sign-up btn navbar-btn" href="{% url 'accounts:signup' %}">
              <span class="glyphicon glyphicon-user"></span> Sign Up<span class="sr-only">(current)</span>
            </a>
          </div>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->

    <!-- Jumbotron background will be image or gallery of images - swimming and product related -->
    <div class="jumbotron">
      <div class="container">
          <h1>Welcome to CoachMate</h1>
          <p>
            News flash: managing your team just got easier. With CoachMate, you can
            keep track of teams and swimmers, write workouts, plan your season, and much more.
            CoachMate is the tool for swim coaches looking to get the most out of each season.
          </p>
          <p><a id="scroll" class="btn btn-primary btn-lg" href="#first-featurette" role="button">Learn more</a></p>
      </div>
    </div>

    <div class="container marketing">

      <!-- Featurettes -->
      <div id="first-featurette" class="row featurette">
          <h2 class="featurette-heading">All your teams in one place.</h2>
          <hr class="featurette-divider">
          <p class="lead">
            Manage all teams and swimmers in one place using one account.
            Separate teams and swimmers to make organizing and planning simple.
          </p>
      </div>

      <div class="row featurette">
          <h2 class="featurette-heading">Write now. <span class="text-muted">Practice later.</span></h2>
          <hr class="featurette-divider">
          <p class="lead">
            Easily write sets, set up a practice, and plan your season week by
            week. You can see what you're focusing on and what needs more attention.
          </p>
      </div>

      <div class="row featurette">
          <h2 class="featurette-heading">We track data so you don't have to.</span></h2>
          <hr class="featurette-divider">
          <p class="lead">
            Track data for every swimmer and analyze progress; know in seconds
            what's working and what isn't. Plus, it's all in one place and available
            everywhere.
          </p>
      </div>

      <script>
        document.getElementById("scroll").addEventListener("click", function() { doScrolling("#first-featurette", 1000);})
      </script>

      <!-- /END THE FEATURETTES -->

      <!-- Footer -->
      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
        <p>&copy; 2017 Henry Gridley · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
      </footer>

    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../static/bootstrap-3.3.7/js/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>


  </body>
</html>