CoachMate/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static

from .settings import base, dev, prod
from home.views import home

urlpatterns = [
    url(r'^$', home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^teams/', include('teams.urls')),
]

if base.DEBUG:
    urlpatterns += static(dev.STATIC_URL, document_root=dev.STATIC_ROOT)
    urlpatterns += static(dev.MEDIA_URL, document_root=dev.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url

from . import views

app_name = 'accounts'
urlpatterns = [
    url(r'^login/$', views.login, name='login'),
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^settings/$', views.settings, name='settings'),
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.home, name='home'),
]

teams/urls.py
from django.conf.urls import url

from . import views

app_name = 'teams'
urlpatterns = [
    # Dashboard
    url(r'^$', views.teamList, name='teamList'),

    # Training views
    url(r'^train/$', views.showTraining, name='showTraining'),
    url(r'^train/create/(?P<t_id>\d+)/$', views.createTraining, name='createTraining'),
    url(r'^train/delete/(?P<t_id>\d+)/$', views.deleteTraining, name='deleteTraining'),

    # Team specific views
    url(r'^(?P<abbr>\w+)/$', views.swimmerList, name='swimmerList'),
    url(r'^(?P<abbr>\w+)/(?P<s_id>\d+)/$', views.swimmerDetail, name='swimmerDetail'),
    url(r'^(?P<abbr>\w+)/schedule/(?P<w_id>\d+)/$', views.practiceSchedule, name='practiceSchedule'),
    url(r'^(?P<abbr>\w+)/practice/(?P<p_id>\d+)/$', views.writePractice, name='writePractice'),
    url(r'^(?P<abbr>\w+)/records/$', views.teamRecords, name='teamRecords'),

    # Delete models
    url(r'^(?P<abbr>\w+)/team/delete/$', views.deleteTeam, name='deleteTeam'),
    url(r'^(?P<abbr>\w+)/swimmer/delete/(?P<s_id>\d+)/$', views.deleteSwimmer, name='deleteSwimmer'),
    url(r'^(?P<abbr>\w+)/practice/delete/(?P<p_id>\d+)/$', views.deletePractice, name='deletePractice'),
    url(r'^(?P<abbr>\w+)/set/delete/(?P<set_id>\d+)/$', views.deleteSet, name='deleteSet'),
]

teams/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from datetime import date, timedelta
from dateutil.relativedelta import relativedelta

from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Swimmers & Teams

class Team(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    abbr = models.CharField(max_length=5)
    region = models.CharField(max_length=25, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_record(self, event):
        """
        Return best time in given event.
        """
        times_men = Event.objects.filter(team=self).filter(event=event[0]).filter(gender='M')
        times_women = Event.objects.filter(team=self).filter(event=event[0]).filter(gender='F')
        result_men = None
        result_women = None
        if times_men.exists():
            result_men = times_men[0]
        if times_women.exists():
            result_women = times_women[0]

        return (event[1], result_men, result_women)

GENDER_CHOICE = (
    ('M', 'Male'),
    ('F', 'Female'),
)
class Swimmer(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)
    f_name = models.CharField(max_length=25)
    l_name = models.CharField(max_length=25)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE)
    birth_date = models.DateField(blank=True, null=True)
    age = models.IntegerField(blank=True, null=True)
    bio = models.TextField(blank=True)
    picture = models.ImageField(null=True, blank=True)

    class Meta:
        ordering = ['l_name', 'f_name']

    def __str__(self):
        return self.l_name

    def __unicode__(self):
        return self.f_name + ' ' + self.l_name

    def set_age(self):
        """
        Calculate and set age field based on birth date.
        """
        if self.birth_date:
            self.age = int((date.today() - self.birth_date).days / 365.2425)
        self.save()
        return self.age

    def get_best_time(self, event):
        """
        Return best time in given event.
        """
        times = self.event_set.filter(event=event)
        if times.exists():
            return times[0]
        else:
            return None

    def get_base(self, pace, stroke):
        """
        Returns a swimmer's base pace for the given stroke and pace.
        """
        try:
            if pace == 'train':
                return self.event_set.filter(event='base ' + stroke)[0].time
            elif pace == 'race':
                base = self.event_set.filter(event='100 ' + stroke)[0]
                return timedelta(seconds=(0.5 * base.time.total_seconds()))
        except IndexError:
            return None

# Calendar

# Events

EVENT_CHOICE = (
    ('50 free', '50 Freestyle'),
    ('100 free', '100 Freestyle'),
    ('200 free', '200 Freestyle'),
    ('500 free', '500 Freestyle'),
    ('1000 free', '1000 Freestyle'),
    ('50 back', '50 Backstroke'),
    ('100 back', '100 Backstroke'),
    ('200 back', '200 Backstroke'),
    ('50 breast', '50 Breaststroke'),
    ('100 breast', '100 Breaststroke'),
    ('200 breast', '200 Breaststroke'),
    ('50 fly', '50 Butterfly'),
    ('100 fly', '100 Butterfly'),
    ('200 fly', '200 Butterfly'),
    ('100 im', '100 IM'),
    ('200 im', '200 IM'),
    ('400 im', '400 IM'),
    ('base free', 'Freestyle Base'),
    ('base back', 'Backstroke Base'),
    ('base breast', 'Breaststroke Base'),
    ('base fly', 'Butterfly Base'),
    ('base IM', 'IM Base'),
)

# Many-to-one -> many times can be created and associated with one swimmer
# Makes it easy to sort and query for fastest time
class Event(models.Model):
    swimmer = models.ForeignKey(Swimmer, on_delete=models.SET_NULL, null=True, blank=True)
    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=50, null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICE, null=True, blank=True)
    event = models.CharField(max_length=10, choices=EVENT_CHOICE)
    time = models.DurationField()
    place = models.IntegerField(null=True, blank=True)
    date = models.DateField(null=True)

    class Meta:
        ordering = ['event', 'time']

    def __str__(self):
        return self.event

    def set_name(self):
        if (not self.name) and self.swimmer:
            self.name = self.swimmer.f_name + ' ' + self.swimmer.l_name
            self.save()
            return True
        else:
            return False

    def set_gender(self):
        if (not self.gender) and self.swimmer:
            self.gender = self.swimmer.gender
            self.save()
            return True
        else:
            return False


# Could add more classes to organize weeks like a calendar or could do it in views
# Need to figure out how to navigate weeks
class Week(models.Model):
    monday = models.DateField(null=True)
    tuesday = models.DateField(null=True)
    wednesday = models.DateField(null=True)
    thursday = models.DateField(null=True)
    friday = models.DateField(null=True)
    saturday = models.DateField(null=True)
    sunday = models.DateField(null=True)
    present = models.BooleanField()

    def __str__(self):
        return self.monday.isoformat()

    def populate(self):
        """
        Fill in date information for all days based on initial Monday.
        """
        self.tuesday = self.monday + relativedelta(days=1)
        self.wednesday = self.monday + relativedelta(days=2)
        self.thursday = self.monday + relativedelta(days=3)
        self.friday = self.monday + relativedelta(days=4)
        self.saturday = self.monday + relativedelta(days=5)
        self.sunday = self.monday + relativedelta(days=6)
        self.save()

    def get_week(self, n):
        """
        Return previous or next Monday.
        """
        if n is 1:
            monday = self.monday + timedelta(days=7)
        else:
            monday = self.monday - timedelta(days=7)

        return Week.objects.get(monday=monday)

    def date_range(self):
        """
        Yields each date in a week.
        """
        start_date = self.monday
        end_date = self.sunday + timedelta(days=1)
        for n in range(int((end_date - start_date).days)):
            yield start_date + timedelta(n)


# Training
FOCUS_CHOICE = (
    ('warmup', 'Warmup'),
    ('technique', 'Technique'),
    ('kick', 'Kick'),
    ('sprint', 'Sprint'),
    ('mid-distance', 'Mid Distance'),
    ('distance', 'Distance'),
    ('race', 'Race'),
    ('cooldown', 'Cooldown'),
)
PACE_CHOICE = (
    ('train', 'Base training pace'),
    ('race', '100 race pace'),
)
GROUP_CHOICE = (
    ('team', 'Team'),
    ('ind', 'Individuals'),
)

# Sets day, week, and team for each group of sets
class Practice(models.Model):
    DAY_CHOICE = (
        ('monday', 'Monday'),
        ('tuesday', 'Tuesday'),
        ('wednesday', 'Wednesday'),
        ('thursday', 'Thursday'),
        ('friday', 'Friday'),
        ('saturday', 'Saturday'),
        ('sunday', 'Sunday'),
    )

    team = models.ForeignKey(Team, on_delete=models.CASCADE, null=True)
    week_id = models.ForeignKey(Week, on_delete=models.CASCADE, null=True)
    weekday = models.CharField(max_length=10, choices=DAY_CHOICE)

    class Meta:
        ordering = ['week_id']

    def __str__(self):
        return self.weekday

# Overall focus and repeats
class Set(models.Model):
    practice_id = models.ForeignKey(Practice, on_delete=models.CASCADE)
    group = models.CharField(max_length=25, choices=GROUP_CHOICE, null=True)
    swimmers = models.ManyToManyField(Swimmer, blank=True)
    focus = models.CharField(max_length=15, choices=FOCUS_CHOICE)
    repeats = models.IntegerField(blank=True, null=True)
    order = models.IntegerField(null=True) # creates order within a practice
    pace = models.CharField(max_length=10, choices=PACE_CHOICE, null=True)

    class Meta:
        ordering = ['practice_id', 'order']

    def __str__(self):
        return self.focus

# Individual items in a set
class Rep(models.Model):
    STROKE_CHOICE = (
        ('fly', 'Butterfly'),
        ('back', 'Backstroke'),
        ('breast', 'Breaststroke'),
        ('free', 'Freestyle'),
        ('IM', 'IM'),
    )

    set_id = models.ForeignKey(Set, on_delete=models.CASCADE)
    num = models.IntegerField()
    distance = models.IntegerField()
    stroke = models.CharField(max_length=6, choices=STROKE_CHOICE)
    rest = models.DurationField(blank=True, null=True)
    comments = models.CharField(max_length=254, blank=True)

    class Meta:
        ordering = ['set_id', 'stroke']

    def __str__(self):
        return self.stroke

class Interval(models.Model):
    swimmer = models.ForeignKey(Swimmer, on_delete=models.CASCADE)
    rep = models.ForeignKey(Rep, on_delete=models.CASCADE)
    time = models.DurationField()

    class Meta:
        ordering = ['swimmer', 'rep', 'time']

    def __str__(self):
        return unicode(self.time)

# Guide for doing interval calculations
class TrainingModel(models.Model):
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.team.abbr

class TrainingMultiplier(models.Model):
    training_model = models.ForeignKey(TrainingModel, on_delete=models.CASCADE)
    focus = models.CharField(max_length=15, choices=FOCUS_CHOICE)
    multiplier = models.CharField(max_length=5, null=True)

    class Meta:
        ordering = ['training_model', 'focus']

    def __str__(self):
        return self.focus

teams/templates/teams/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'bootstrap/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.css"/>
    <link rel="stylesheet" href="{% static 'teams/css/base.css' %}">
    {% block stylesheets %}{% endblock %}

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static 'bootstrap/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- DataTables CSS -->
    <link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.15/css/jquery.dataTables.css">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>

    <!-- Nav -->
    <nav class="navbar navbar-fixed-top">
      <div class="container-fluid">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'teams:teamList' %}">CoachMate</a>
        </div>

          <!-- Account dropdown -->
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Profile<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li class="dropdown-header">{{ user.first_name }} {{ user.last_name }}</li>
                <li><a href="{% url 'accounts:settings' %}">Account</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="#">Help</a></li>
                <li role="separator" class="divider"></li>
                <li><a href="{% url 'accounts:logout' %}">Log out</a></li>
              </ul>
            </li>
          </ul>

          <!-- May remove -->
          <!--
          <form class="navbar-form navbar-right" action="" method="post">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search" name="search">
              <div class="input-group-btn">
                  <button class="btn btn-default" type="submit">
                    <i class="glyphicon glyphicon-search"></i>
                  </button>
              </div>
            </div>
          </form>
          -->

        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <!-- Sidebar -->
        <div class="col-sm-3 col-md-2 sidebar">

          {% block sidebar %}
            <ul class="nav nav-sidebar">
              <li class="header">General</li>
              <li class="dashboard"><a href="{% url 'teams:teamList' %}">Teams</a></li>
              <li class="training"><a href="{% url 'teams:showTraining' %}">Training</a></li>
            </ul>

            {% if team %}
              <ul class="nav nav-sidebar">
                <li class="header">{{ team.abbr }}</li>
                <li class="team"><a href="{% url 'teams:swimmerList' team.abbr %}">Swimmers</a></li>
                <li class="practice"><a href="{% url 'teams:practiceSchedule' team.abbr 0 %}">Practice</a></li>
                <li class="records"><a href="{% url 'teams:teamRecords' team.abbr %}">Records</a></li>
              </ul>
            {% endif %}
          {% endblock %}
        </div>

        <!-- Main block -->
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">{% block page-title %}Placeholder{% endblock %}</h1>

          <h2 class="sub-header">{% block table-title %}Placeholder{% endblock %}</h2>

          <!-- Modal -->
          {% block modal %}{% endblock %}

          <!-- Table/content -->
          {% block content %}{% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!--<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>-->
    <script src="{% static 'home/js/jquery-3.2.1.min.js' %}"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- DataTables core JavaScript -->
    <script type="text/javascript" src="https://cdn.datatables.net/v/bs/dt-1.10.15/datatables.min.js"></script>
    <!--
    <script type="text/javascript" charset="utf8" src="//cdn.datatables.net/1.10.15/js/jquery.dataTables.bootstrap.js"></script>
  -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static 'bootstrap/js/ie10-viewport-bug-workaround.js' %}"></script>

    <!-- Additional scripts -->
    <!-- Enable popovers -->
    <script>
      $(document).ready(function() {
        $('[data-toggle="popover"]').popover();
      });
    </script>
    {% block scripts %}{% endblock %}
  </body>
</html>

teams/templates/teams/practice_schedule.html
<!DOCTYPE html>
{% extends "teams/base.html" %}
{% load static from staticfiles %}
{% load datetime_filter %}
<html lang="en">
  <head>
    {% block title %}Practice Schedule - {{ team.abbr }}{% endblock %}
    {% block stylesheets %}
      <link rel="stylesheet" href="{% static 'teams/css/practice_schedule.css' %}">
    {% endblock %}
  </head>

  <body>
    {% block sidebar %}
      {{ block.super }}

      <ul class="nav nav-sidebar">
        <li class="header">Practices</li>
        <li><a href="" data-toggle="modal" data-target="#baseModal">Add Practice</a></li>
      </ul>
    {% endblock %}

    {% block page-title %}{{ team.name }}{% endblock %}
    {% block table-title %}
      Schedule ({{ current.monday|date:"m/d/y" }} - {{ current.sunday|date:"m/d/y" }})
    {% endblock %}

    {% block modal %}
      <div id="baseModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">
                Add a Practice
              </h4>
            </div>

            <div class="modal-body">
              <form action="{% url 'teams:practiceSchedule' team.abbr current.id %}" method="post" class="form-signin">
                {% csrf_token %}
                {% if practice_form.errors %}
                  {% for field in practice_form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger" style="text-align: center">
                          <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endfor %}
                {% endif %}

                <!-- Practice form: sets weekday -->
                {% for field in practice_form %}
                  {{ field.label }}<br>
                  {{ field }}
                {% endfor %}

                <br>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-md btn-primary">Next</button>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </form>
            </div>

          </div>

        </div>
      </div>
    {% endblock %}

    {% block content %}
      <div class="panel-group" id="accordion">
        <!-- Loop through each practice and display them on each day -->
        <!-- 'Day' sets panel headings even if there is no practice that day -->
        {% for practice, day in practices %}

          <div class="panel panel-info">
            <div class="panel-heading" data-toggle="collapse" data-parent="#accordion" href="#collapse{{ forloop.counter }}">
              <h4 class="panel-title">
                {{ day|title }}
                {% for field, value in dates %}
                  {% if field == day %}
                    - {{ value|date:"m/d" }}
                  {% endif %}
                {% endfor %}
              </h4>
            </div>

            <div id="collapse{{ forloop.counter }}" class="panel-collapse collapse">
              <div class="panel-body">
                <!-- Display practice: same format as when writing -->
                {% if practice.0 %}
                  {% for set in practice.1 %}

                    <h3>
                      {{ set.0.order }})
                      {{ set.0.focus|title }}
                      {% if set.0.repeats %}
                         - {{ set.0.repeats }}x
                      {% endif %}
                    </h3>

                    <div class="reps">
                      {% for rep in set.0.rep_set.all %}
                        {{ rep.num }} x {{ rep.distance }} {{ rep.stroke }}
                        {% if rep.rest %}
                          @ {{ rep.rest|format_duration }} rest
                        {% endif %}
                        {% if rep.comments %}
                          - {{ rep.comments|capfirst }}
                        {% endif %}
                      {% endfor %}
                      <br>
                    </div>

                    <div class="table table-responsive">
                      <table class="table table-striped intervals">
                        <thead>
                          <tr>
                            <td></td>
                            <!-- Reps in each set -->
                            {% for rep in set.0.rep_set.all %}
                              <td>{{ rep.num }}x{{ rep.distance }} {{ rep.stroke }}</td>
                            {% endfor %}
                          </tr>
                        </thead>
                        <tbody>
                          {% for swimmer in set.1 %}
                            <tr>
                              <td>{{ swimmer.0.f_name }} {{ swimmer.0.l_name }}</td>
                              <!-- List the interval for each rep for each swimmer -->
                              {% for rep in swimmer.1 %}
                                {% if rep.0.rest %}
                                  <td>{{ rep.0.rest|format_duration }} rest</td>
                                {% elif rep.1 %}
                                  <td>{{ rep.1.time|format_duration }}</td>
                                {% else %}
                                  <td>--</td>
                                {% endif %}
                              {% endfor %}
                            </tr>
                          {% endfor %}
                        </tbody>
                      </table>
                    </div>

                  {% endfor %}
                  <br>

                  <!-- Delete practice -->
                  <a href="{% url 'teams:deletePractice' team.abbr practice.0.id %}" type="button" class="btn btn-danger btn-md pull-right follow-link" style="margin-left: 5px">
                    <span class="glyphicon glyphicon-remove-circle"></span>
                  </a>
                  <!-- Edit practice -->
                  <a href="{% url 'teams:writePractice' team.abbr practice.0.id %}" type="button" class="btn btn-default btn-md pull-right follow-link" style="margin-left: 5px">
                    <span class="glyphicon glyphicon-pencil"></span>
                  </a>
                {% endif %}
              </div>
            </div>

          </div>
        {% endfor %}
      </div>
      <a href="{% url 'teams:practiceSchedule' team.abbr previous.id %}" type="button" class="btn btn-primary btn-md pull-left">
        <span class="glyphicon glyphicon-circle-arrow-left"></span>
      </a>
      <a href="{% url 'teams:practiceSchedule' team.abbr next.id %}" type="button" class="btn btn-primary btn-md pull-right" style="margin-left: 5px">
        <span class="glyphicon glyphicon-circle-arrow-right"></span>
      </a>
    {% endblock %}

    {% block scripts %}
      <!-- Highlights sidebar links according to page -->
      <script>
        $(function() {
          $('.practice').addClass('active');
        });
      </script>

      <!-- Fixes bug where links would collapse panels instead of follow link -->
      <script>
        $('.follow-link').click(function(e) {
          e.stopPropagation();
        })
      </script>
    {% endblock %}
  </body>

</html>

teams/templates/teams/team_list.html
<!DOCTYPE html>
{% extends "teams/base.html" %}
{% load static from staticfiles %}
<html lang="en">
  <head>
    {% block title %}Dashboard{% endblock %}
    {% block stylesheets %}
      <link rel="stylesheet" type="text/css" href="{% static 'teams/css/team_list.css' %}">
    {% endblock %}
  </head>

  <body>
    {% block page-title %}Dashboard{% endblock %}
    {% block table-title %}Teams{% endblock %}

    {% block sidebar %}
      {{ block.super }}

      <ul class="nav nav-sidebar">
        <li class="header">Teams</li>
        <li><a href="" data-toggle="modal" data-target="#baseModal">Add Team</a></li>
      </ul>
    {% endblock %}

    {% block modal %}
      <div id="baseModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

          <!-- Modal content-->
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal">&times;</button>
              <h4 class="modal-title">
                Add a Team
              </h4>
            </div>

            <div class="modal-body">
              <form action="{% url 'teams:teamList' %}" method="post" class="form-signin">
                {% csrf_token %}
                {% if team_form.errors %}
                  {% for field in team_form %}
                    {% for error in field.errors %}
                      <div class="alert alert-danger" style="text-align: center">
                          <strong>{{ error|escape }}</strong>
                      </div>
                    {% endfor %}
                  {% endfor %}
                {% endif %}

                <!-- Team form -->
                {% for field in team_form %}
                  {{ field }}
                {% endfor %}

                <br>
                <div class="modal-footer">
                  <button type="submit" class="btn btn-md btn-primary">Finish</button>
                  <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
              </form>
            </div>

          </div>

        </div>
      </div>
    {% endblock %}

    {% block content %}
      {% if team_list %}
        <!-- Display team in table -->
        <div class="table-responsive">
          <table id="teams" class="hover stripe">
            <thead>
              <tr>
                <th></th>
                <th>Name</th>
                <th>Abbr</th>
                <th>Region</th>
                <th>Swimmers</th>
              </tr>
            </thead>
            <tbody>
              {% for team in team_list %}
                <tr class="clickable-row" data-href="{% url 'teams:swimmerList' team.abbr %}">
                  <td>{{ forloop.counter }}</td>
                  <td>{{ team.name }}</a></td>
                  <td>{{ team.abbr }}</td>
                  <td>{{ team.region }}</td>
                  <td>{{ team.swimmer_set.all|length }}</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>

      {% else %}

      <!-- Display prompts if no teams -->
        <div id="first-featurette" class="row featurette empty-team">
          <h2 class="featurette-heading empty-dialogue">
            No teams yet
          </h2>
        </div>
      {% endif %}
    {% endblock %}

    {% block scripts %}
      <!-- Highlights sidebar links according to page -->
      <script>
        $(function() {
          $('.dashboard').addClass('active');
        });
      </script>

      <!-- Makes table rows clickable -->
      <script>
        $(function() {
          $(".clickable-row").click(function() {
            window.location = $(this).data("href");
          });
        });
      </script>

      <!-- Create DataTable from team table -->
      <!-- Need to figure out how to make each entry a link -->
      <script>
        $(document).ready( function () {
          $('#teams').DataTable();
        } );
      </script>

      <!-- Format info and pagination buttons below table -->
      <script>
        $(document).ready(function() {
          $('div.col-sm-5').removeClass('col-sm-5').addClass('col-xs-12 col-md-5 info-pag');
          $('div.col-sm-7').removeClass('col-sm-7').addClass('col-xs-12 col-md-7 info-pag');
        });
      </script>
    {% endblock %}
  </body>
</html>